### ISSUE TITLE
./psdev tokens cumulative colum is a little off

### ISSUE THREAD

**Issue by barrywhitehat1** [Giveth/WHGBalanceVerification#12]
It starts with 366850000980000000000000000 when it should be 249999990000000000000000

@p-s-dev if you have time to take a look we would really appreciate it :)

**Comment by ghost** [comment]
Thanks for noticing this.  I made a PR to fix https://github.com/Giveth/WHGBalanceVerification/pull/13

**Comment by barrywhitehat1** [comment]
no probs. Thanks for always helping out :)
